-- Part 2.1 schema.sql
--
-- Submitted by: <Your Name>, <Your Student Number>
-- 

-- DO NOT use these SQL commands in your submission(they will cause an 
--  error on the NMS database server):
-- CREATE SCHEMA 
-- USE 

CREATE TABLE MARKET (
	NAME 			VARCHAR()	NOT NULL,
	POSTCODE[PK]	VARCHAR(7)	NOT NULL,

	PRIMARY KEY(POSTCODE),
);

CREATE TABLE FOOD_TRUCK (
	VRN[PK]			    CHAR(7)		NOT NULL,	
	SALE_COUNT		    INTEGER		NOT NULL,
	DATE_PUT_SERVICE	DATE		NOT NULL,
	MARKET_POSTCODE    	VARCHAR(),

	PRIMARY KEY(VRN),
	FOREIGN KEY(MARKET_POSTCODE) REFERENCES MARKET(POSTCODE) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER (
	FIRST_NAME 			VARCHAR()	NOT NULL,
	LAST_NAME			VARCHAR()	NOT NULL,
	DOB				    DATE		NOT NULL,
	HOUSE_NUM			INTEGER		NOT NULL,
	STREET_NAME			VARCHAR()	NOT NULL,
	POSTCODE	 		VARCHAR()	NOT NULL,
	EMAIL[PK]			VARCHAR()	NOT NULL,
	BURRITOCLUB			BOOLEAN		NOT NULL,
	BURRITO_COUNT       INTEGER		AUTO_INCREMENT,

	PRIMARY KEY(EMAIL)
);

CREATE TABLE MEAL_ORDER (
	ORDER_NO	    INTEGER		NOT NULL	AUTO_INCREMENT,
	ITEM_ID         INTEGER		NOT NULL,
	ORDER_DATE		DATE		NOT NULL,
	MARKET			VARCHAR()	NOT NULL,
	FOOD_TRUCK_VRN	CHAR(7)		NOT NULL,
	NO_OF_BUR		INTEGER		NOT NULL,
	NO_OF_BEV		INTEGER		NOT NULL,
	TOTAL_COST		DOUBLE		NOT NULL,

	PRIMARY KEY(ORDER_NO)
);

CREATE TABLE BURRITO (
	ITEM_ID[PK]				INTEGER		NOT NULL,
	FILLING					VARCHAR()	NOT NULL,
	BEAN					VARCHAR()	NOT NULL,
	BUR_SIZE                VARCHAR()	NOT NULL,
	DESCRIPTION				VARCHAR()	NOT NULL,
	BUR_PRICE	            DOUBLE		NOT NULL,
	FREE_BUR_OFFER			BOOLEAN		NOT NULL,

	PRIMARY KEY(ITEM_ID)
	-- CREATE DOMAIN BUR_SIZE for Mini, Regular & Grande?
);

CREATE TABLE BURRITO_TOPPING (
	BUR_ID     		   INTEGER		NOT NULL,		
	TOPPING_TYPE	   VARCHAR(50)	NOT NULL,
	TOPPING_PRICE      DOUBLE		NOT NULL,	

	PRIMARY KEY(BUR_ID, TOPPING_TYPE, TOPPING_PRICE),
	FOREIGN KEY(BUR_ID) REFERENCES BURRITO(ITEM_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE BEVERAGE (
	ITEM_ID        			INTEGER		NOT NULL,
	NAME					VARCHAR(50),
	BEV_SIZE_ML             INTEGER    	NOT NULL,
	-- CREATE DOMAIN BEV_SIZE_ML to be three sizes 0f, 250ml, 400ml & 500ml?
	ALCOHOLIC      			BOOLEAN,		
	DESCRIPTION				VARCHAR()	NOT NULL,
	PRICE          			DOUBLE		NOT NULL,

	PRIMARY KEY(ITEM_ID)
);

CREATE TABLE MARKET_DAYS_ACTIVE (
	MARKET_POSTCODE	VARCHAR(7)	NOT NULL,	
	DAY_ACTIVE		DATE		NOT NULL,
	PRIMARY KEY(MARKET_POSTCODE, DAYS_ACTIVE),
	FOREIGN KEY(MARKET_POSTCODE) REFERENCES MARKET(POSTCODE) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ORDER_CONTAINS_BUR (
	ORDER_NO       	INTEGER		NOT NULL,
	BUR_ID     		INTEGER		NOT NULL,
	FOREIGN KEY(ORDER_NO) REFERENCES MEAL_ORDER(ORDER_NO) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(BUR_ID) REFERENCES BURRITO(ITEM_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ORDER_CONTAINS_BEV (
	ORDER_NO		INTEGER		NOT NULL,
	BEV_ID	    	INTEGER		NOT NULL,
	FOREIGN KEY(ORDER_NO) REFERENCES MEAL_ORDER(ORDER_NO) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(BEV_ID) REFERENCES BEVERAGE(ITEM_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER_BUYS_ORDER (
	ORDER_NO       	INTEGER		NOT NULL,
	CUSTOMER_EMAIL	VARCHAR(50)	NOT NULL,
	FOREIGN KEY(ORDER_NO) REFERENCES MEAL_ORDER(ORDER_NO) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(CUSTOMER_EMAIL) REFERENCES CUSTOMER(EMAIL) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CUSTOMER_BUYS_FROM_FOOD_TRUCK (
	CUSTOMER_EMAIL	VARCHAR(50)	NOT NULL,
	FOOD_TRUCK_VRN	CHAR(7)		NOT NULL,
	FOREIGN KEY(CUSTOMER_EMAIL) REFERENCES CUSTOMER(EMAIL) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(FOOD_TRUCK_VRN) REFERENCES FOOD_TRUCK(VRN) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE FOOD_TRUCK_SELLS_ORDER (
	FOOD_TRUCK_VRN	CHAR(7)		NOT NULL,
	ORDER_NO		INTEGER  	NOT NULL,
	FOREIGN KEY(FOOD_TRUCK_VRN) REFERENCES FOOD_TRUCK(VRN) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(ORDER_NO) REFERENCES MEAL_ORDER(ORDER_NO) ON DELETE RESTRICT ON UPDATE CASCADE
);